version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: api-sport-training:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TrainingProgramsDatabase__ConnectionString=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:${MONGO_HOST_PORT}/${MONGO_DB_NAME}?authSource=admin
      - TrainingProgramsDatabase__DatabaseName=${MONGO_DB_NAME}
    depends_on:
      mongodb:  
        condition: service_healthy 
    restart: unless-stopped
    networks:  
      - app-network
    

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "${MONGO_HOST_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5


networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: