@client-certification-check = disabled
@API-sport-training-program_HostAddress = https://localhost:5276

GET {{API-sport-training-program_HostAddress}}/api/programs
Accept: application/json

###
GET http://127.0.0.1:5276/api/programs

###